package com.graduation.hiredhub.entity.enumeration;

public enum NotificationType {
    APPLICATION_SUCCESS,
    EMPLOYER_RESPONSE,
    APPLICATION_STATUS_UPDATE,
    APPLICATION_CV_UPDATE,
    JOB_POST_EXPIRY,
    NEW_CANDIDATE,
    FAVORITE_JOB_REMINDER,
    FOLLOWED_COMPANY_NEW_POST,
    SYSTEM_UPDATE,
    PROFILE_COMPLETION_REMINDER,
    JOB_POST_RENEWAL,
    ACCOUNT_REGISTRATION_SUCCESS,
    POSTING_STATUS_CHANGE,

}
