package com.graduation.hiredhub.entity.enumeration;

public enum NotificationType {
    JOB_MATCH,
    APPLICATION_SUCCESS,
    EMPLOYER_RESPONSE,
    APPLICATION_STATUS_UPDATE,
    INTERVIEW_INVITE,
    JOB_POST_EXPIRY,
    NEW_CANDIDATE,
    FAVORITE_JOB_REMINDER,
    JOB_POST_APPROVED,
    EMPLOYER_INVITE,
    SYSTEM_UPDATE,
    PROFILE_COMPLETION_REMINDER,
    PROMOTION_OFFER,
    JOB_POST_RENEWAL,
    ACCOUNT_REGISTRATION_SUCCESS
}
