server:
  port: 8888
  servlet:
    context-path: /api/v1

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: HiredHub
  datasource:
    url: jdbc:mysql://localhost:3308/hired_hub?createDatabaseIfNotExist=true
    username: hiredhub
    password: hiredhub
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: localhost
    port: 6379
  mail:
    username: langxuatchieu@gmail.com
    host: smtp.gmail.com
    port: 587
    password: lzzq inof jkgv emxj
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: hired-hub

jwt:
  secret: 94b8901a1660a7c61ca10349a17b5b99d6535590f440afdb7d17045cc43f776c624826766ff013eb6de391cf784c5e6a20da31453c0c46d4cb05376c55f29b59
  expiration: 30
  refreshable: 3

logging:
  level:
    org:
      springframework:
        security=DEBUG:
#path:
#  url:
