server:
  port: 8888
#  servlet:
#    context-path: /identity

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: HiredHub
  datasource:
    url: jdbc:mysql://localhost:3308/hired_hub?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: Hay0Nhac1Nho2Ban3Than4Rang5Sap6Chuyen7Nha8Roi
  expiration: 30
  refreshable: 3

#path:
#  url: